Repository privML/privacy-evaluator, pull requests merged in 2021-06, with the labels that each got.

#86 Restructure codebase for membership inference attack on point basis
  notebooks/membership_inference_attack.ipynb
  privacy_evaluator/attacks/attack.py
  privacy_evaluator/attacks/membership_inference/black_box.py
  privacy_evaluator/attacks/membership_inference/black_box_rule_based.py
  privacy_evaluator/attacks/membership_inference/label_only_decision_boundary.py
  privacy_evaluator/attacks/membership_inference/membership_inference.py
  privacy_evaluator/attacks/sample_attack.py
  privacy_evaluator/classifiers/classifier.py
  privacy_evaluator/metrics/basics.py
  requirements.txt
  tests/attacks/attack_test.py
  tests/attacks/membership_inference/black_box_rule_based_test.py
  tests/attacks/membership_inference/black_box_test.py
  tests/attacks/membership_inference/label_only_boundry_distance_test.py
  tests/attacks/membership_inference/membership_inference_test.py
  tests/attacks/sample_attack_test.py
Labels: enhancement, team1

#112 Style: Switch to local imports
  privacy_evaluator/__init__.py
  privacy_evaluator/attacks/__init__.py
  privacy_evaluator/attacks/attack.py
  privacy_evaluator/attacks/membership_inference/__init__.py
  privacy_evaluator/attacks/membership_inference/black_box.py
  privacy_evaluator/attacks/membership_inference/black_box_rule_based.py
  privacy_evaluator/attacks/membership_inference/label_only_decision_boundary.py
  privacy_evaluator/attacks/membership_inference/membership_inference.py
  privacy_evaluator/attacks/sample_attack.py
  privacy_evaluator/classifiers/__init__.py
  privacy_evaluator/datasets/__init__.py
  privacy_evaluator/datasets/cifar10.py
  privacy_evaluator/metrics/__init__.py
  privacy_evaluator/metrics/privacy_risk_score.py
  privacy_evaluator/models/__init__.py
  privacy_evaluator/models/tf/__init__.py
  privacy_evaluator/models/tf/dcti/__init__.py
  privacy_evaluator/models/tf/dcti/_train_dcti.py
  privacy_evaluator/models/torch/__init__.py
  privacy_evaluator/models/torch/dcti/__init__.py
  privacy_evaluator/models/torch/dcti/_train_dcti.py
  privacy_evaluator/output/__init__.py
Labels: enhancement, team1

#102 Team2sprint2
  .github/workflows/styling.yml
  .github/workflows/testing.yml
  .gitignore
  README.md
  SUPPORTER_LIST.md
  demo/train-cifar10-torch/train.py
  demo/train_cifar10_tf/data.py
  demo/train_cifar10_tf/main.py
  demo/train_cifar10_tf/metric.py
  demo/train_cifar10_tf/model.py
  demo/train_cifar10_tf/train.py
  demo/train_cifar10_torch/data.py
  demo/train_cifar10_torch/main.py
  demo/train_cifar10_torch/metric.py
  demo/train_cifar10_torch/model.py
  demo/train_cifar10_torch/train.py
  docs/Property_Interference_Attacks.png
  privacy_evaluator/attacks/__init__.py
  privacy_evaluator/attacks/attack_interface.py
  privacy_evaluator/attacks/property_inference_attack.py
  privacy_evaluator/metrics/accuracy.py
  privacy_evaluator/models/README.md
  privacy_evaluator/models/__init__.py
  privacy_evaluator/models/torch/_train_dcti.py
  privacy_evaluator/models/torch/dcti.py
  privacy_evaluator/models/train_cifar10_tf/data.py
  privacy_evaluator/models/train_cifar10_tf/main.py
  privacy_evaluator/models/train_cifar10_tf/metric.py
  privacy_evaluator/models/train_cifar10_tf/model.py
  privacy_evaluator/models/train_cifar10_tf/train.py
  privacy_evaluator/models/train_cifar10_torch/__init__.py
  privacy_evaluator/models/train_cifar10_torch/data.py
  privacy_evaluator/models/train_cifar10_torch/main.py
  privacy_evaluator/models/train_cifar10_torch/metric.py
  privacy_evaluator/models/train_cifar10_torch/model.py
  privacy_evaluator/models/train_cifar10_torch/train.py
  tests/attacks/class_test.py
  tests/attacks/property_inference_test.py
  tests/attacks/sample_attack_test.py
  tests/metrics/test_accuracy.py
Labels: team2

#183 initial injection of interpretations into the library #154
  privacy_evaluator/attacks/membership_inference/membership_inference.py
  privacy_evaluator/attacks/membership_inference/membership_inference_analysis.py
  privacy_evaluator/output/user_output_privacy_score.py
Labels: team1

#186 Feat/115 finalize mia descriptions in readme
  README.md
Labels: team1
